# pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: html-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    # ReadWriteOnce - только pod-ы внутри одного node могут читать и писать в этот volume
    # ReadOnlyMany - pod-ы внутри разных node могут читать этот volume
    # ReadWriteMany - pod-ы внутри разных node могут читать и писать в этот volume (нужны дополнительные настройки)
    # ReadWritePod - контейнеры внутри одного pod могут читать и писать в этот volume (нужны дополнительные настройки)
    - ReadOnlyMany
  # storageClassName - класс хранилища, который будет использоваться для создания volume
  hostPath:  # локальный путь на твоей машине
    path: /data  # 🔁 укажи полный путь к своей html-папке
  persistentVolumeReclaimPolicy: Retain
