apiVersion: v1
kind: Pod
metadata:
  name: shvm-pod
  labels:
    app: frontend
spec:
  containers:
  - name: frontend
    image: nginx:latest
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
