apiVersion: v1
kind: Service
metadata:
  name: shvm-service-2
spec:
  selector:
    app: backend
  ports:
  - port: 80 # порт сервиса
    targetPort: 80 # порт контейнера в pod-e
  type: ClusterIP
  # type: LoadBalancer
