global:
  scrape_interval: 5s  # Интервал сбора метрик

scrape_configs:
  - job_name: 'triton'
    static_configs:
      - targets: ['triton:8002']  # Сбор метрик с Triton

  - job_name: 'vllm'
    static_configs:
      - targets: ['vllm:8080']  # Сбор метрик с Triton