{
 "title": "Тритон метрики",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Аналитика времени", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Общее время запроса",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "nv_inference_request_duration_us",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время инпута",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nv_inference_compute_input_duration_us",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время аутпута",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "nv_inference_compute_output_duration_us",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Время инференса (forward pass)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "nv_inference_compute_infer_duration_us",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Аналитика запросов", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Сколько раз обращались к модели (amount/batch_size)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    { "expr": "nv_inference_exec_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Число инференсов (число прогнанных запросов)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    { "expr": "nv_inference_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Число успешных запросов по апи",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    { "expr": "nv_inference_request_success", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Число падений запросов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    { "expr": "nv_inference_request_failure", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Размер батча",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum by (model,version) (rate(nv_inference_count{job=\"triton\"}[10s])/rate(nv_inference_exec_count{job=\"triton\"}[10s]) )",
     "legendFormat": "{{model}}-{{version}}"
    }
   ]
  },
  {
   "title": "Число запросов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum by (model,version) (rate(nv_inference_request_success{job=\"triton\"}[10s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Аналитика утилизации", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Доля GPU утилизации памяти",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    { "expr": "nv_gpu_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "GPU потребление энергии",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    { "expr": "nv_energy_consumption", "legendFormat": "__auto" }
   ]
  }
 ]
}